"""empty message

Revision ID: 20308006182
Revises: 900693d687
Create Date: 2015-01-17 21:46:32.711365

"""

# revision identifiers, used by Alembic.
revision = '20308006182'
down_revision = '900693d687'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('fan_speed', sa.Integer(), nullable=True),
    sa.Column('heat_settings', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roasters')
    ### end Alembic commands ###
