"""empty message

Revision ID: 411338af42b
Revises: 3d3867b0656
Create Date: 2015-01-17 16:39:21.062393

"""

# revision identifiers, used by Alembic.
revision = '411338af42b'
down_revision = '3d3867b0656'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beans')
    op.drop_table('countries')
    op.drop_table('resellers')
    ### end Alembic commands ###
