"""empty message

Revision ID: 900693d687
Revises: 3d4f46dc6dc
Create Date: 2015-01-17 17:03:55.948311

"""

# revision identifiers, used by Alembic.
revision = '900693d687'
down_revision = '3d4f46dc6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('countries', sa.Column('region_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'region_id')
    op.drop_table('regions')
    ### end Alembic commands ###
